<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="PharmacySales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sale" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SaleID" type="xs:integer"/>
                            <xs:element name="CashierName" type="xs:string"/>
                            <xs:element name="TotalAmount" type="xs:decimal"/>
                            <xs:element name="AmountPaid" type="xs:decimal"/>
                            <xs:element name="ChangeAmount" type="xs:decimal"/>
                            <xs:element name="SaleDate" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>